---
clickhouse_version: "22.3.3.44"
clickhouse_packages:
  - clickhouse-client
  - clickhouse-server
  - clickhouse-common-static
clickhouse_syslog_table_query: |
  CREATE TABLE logs.syslogd (
  PRIORITY TINYINT,
  SYSLOG_FACILITY TINYINT,
  SYSLOG_IDENTIFIER String,
  host String,
  message String,
  source_type String,
  timestamp DateTime)
  ENGINE = MergeTree
  ORDER BY timestamp;
clickhouse_server_config_file: "/etc/clickhouse-server/config.xml"
clickhouse_client_config_file: "/etc/clickhouse-server/users.xml"
clickhouse_server_listen_ip_address: "0.0.0.0"
